# Generated by Django 3.1.2 on 2021-01-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empadd',
            new_name='add',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='empid',
            new_name='eid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='empname',
            new_name='name',
        ),
    ]
