# Generated by Django 3.1.2 on 2021-02-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=50)),
            ],
        ),
    ]
